INSERT INTO student VALUES ('ah1zy', 'abdeltawabette', 'Abdeltawabette', '',  'Smith', '2000-01-01', 1111112, 'Number Two Abdeltawab Boulevard', 'Number Two Abdeltawab Boulevard', 4, 'Graduate', 2);
INSERT INTO student VALUES ('ah1zz', 'abdeltawab', 'Abdeltawab', '',  'Jones', '2000-01-01', 1111111, 'Number One Abdeltawab Boulevard', 'Number One Abdeltawab Boulevard', 2, 'Undergraduate', 2);
INSERT INTO student VALUES ('ah1zx', 'abdeltawizzle', 'Abdeltawizzle', '',  'Wizzle', '2000-01-01', 1111113, 'Number Three Abdeltawab Boulevard', 'Number Three Abdeltawab Boulevard', 1, 'Undergraduate', 1);
INSERT INTO student VALUES ('ah1zw', 'abdeltabob', 'Abdeltabob', '',  'Roberts', '2000-01-01', 1111114, 'Number Four Abdeltawab Boulevard', 'Number Four Abdeltawab Boulevard', 3, 'Undergraduate', 1);
INSERT INTO advisor VALUES('ah1zz', 'ab1dr');
INSERT INTO advisor VALUES ('ah1zy', 'ab1fl');
INSERT INTO advisor VALUES('ah1zx', 'ab1ao');
INSERT INTO advisor VALUES ('ah1zw', 'ab1ao'); 
INSERT INTO student_department VALUES('CS', 'ah1zz', 1);
INSERT INTO student_department VALUES('ECE', 'ah1zy', 1);
INSERT INTO student_department VALUES('ANTH', 'ah1zx', 1);
INSERT INTO student_department VALUES('ANTH', 'ah1zw', 1);
INSERT INTO student_department VALUES('ASTR', 'ah1zw', 0);
INSERT INTO prerequisites VALUES('CS', 2150, 'CS', 2110, 'C');
INSERT INTO prerequisites VALUES('CS', 2150, 'CS', 2102, 'C-');
INSERT INTO prerequisites VALUES('CS', 3330, 'CS', 2150, 'C-');
INSERT INTO prerequisites VALUES('CS', 4102, 'CS', 2102, 'C-');
INSERT INTO prerequisites VALUES('ECE', 2660, 'ECE', 2630, 'C-');
INSERT INTO prerequisites VALUES('ECE', 3750, 'ECE', 2660, 'D-');
INSERT INTO degree_requirements VALUES ('CS', 'CS', 1110);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 2110);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 2102);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 2150);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 2330);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 2190);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 3102);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 3330);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 3240);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 4414);
INSERT INTO degree_requirements VALUES ('CS', 'CS', 4102);
INSERT INTO degree_requirements VALUES ('ECE', 'ECE', 2630);
INSERT INTO degree_requirements VALUES ('ECE', 'ECE', 2660);
INSERT INTO degree_requirements VALUES ('ECE', 'ECE', 3750);
INSERT INTO degree_requirements VALUES ('ASTR', 'ASTR', 1210);
INSERT INTO degree_requirements VALUES ('ASTR', 'ASTR', 3130);
INSERT INTO degree_requirements VALUES ('ANTH', 'ANTH', 1010);
INSERT INTO degree_requirements VALUES ('ANTH', 'ANTH', 3010);
INSERT INTO degree_requirements VALUES ('ANTH', 'ANTH', 4591);